adata_path: "/home/arc85/Desktop/Cellinguist/cytokine_dict_ser_sub_full_genes_ad_251118.h5ad"
gene_key: "gene"
layer: null
cond_key: null

gene_emb_tsv: "/home/arc85/Desktop/cellinguist_results_251125/01_cytokine_testing_251125/03_output/cytokines_test_cbow_full_genome_gene_embeddings_251125.tsv.gz"

# model
latent_dim: 32
hidden_dim: 256
n_hidden_layers: 2
cond_emb_dim: 16
input_transform: "log1p"
freeze_gene_embeddings: true

# loss
kl_weight: 1.0

# training
lr: 0.0003
weight_decay: 0.0
batch_size: 256
epochs: 50
num_workers: 4
device: "cuda"
grad_clip_norm: 1.0
seed: 0

# checkpoints
checkpoint_dir: "/home/arc85/Desktop/cellinguist_results_251125/vae_ckpts"
run_name: "cytokines_vae_zinb"
resume_from: null
save_every: 1
